import assert from "node:assert/strict";
import {EventEmitter} from "node:events";
import fs from "node:fs";import os from "node:os";import path from "node:path";
import {test} from "node:test";
import {runQualification,writePrivateEvidence} from "./qualification-client.mjs";
function fixture({move=true,health=20,dimension="minecraft:overworld",bad=false}={}){
 const calls=[],controls=[],bot=new EventEmitter();bot.entity={position:{x:0,y:64,z:0}};bot.health=20;bot.game={dimension};bot.setControlState=(k,v)=>controls.push([k,v]);bot.quit=async()=>{bot.closed=true};
 const reply=field=>bad?"I moved successfully":field==="Pos"?`PilotProbe has the following entity data: [${bot.entity.position.x}d, 64d, ${bot.entity.position.z}d]`:field==="Dimension"?`PilotProbe has the following entity data: "${dimension}"`:`PilotProbe has the following entity data: ${health}f`;
 const rcon={send:async command=>{calls.push(command);return reply(command.split(" ").at(-1))},end:async()=>{rcon.closed=true}};let evidence;
 return {calls,controls,bot,rcon,get evidence(){return evidence},args:{createBot:async options=>{assert.deepEqual(options,{host:"127.0.0.1",port:25585,username:"PilotProbe",auth:"offline"});return bot},connectRcon:async options=>{assert.deepEqual(options,{host:"127.0.0.1",port:25595});return rcon},sleep:async ms=>{if(ms===1000&&move)bot.entity.position.z=1},readyTimeoutMs:20,writeEvidence:async value=>{evidence=value}}};
}
test("fixed movement qualification passes only independent matching evidence",async()=>{const f=fixture();const r=await runQualification(f.args);assert.equal(r.status,"passed");assert.equal(r.claimsLiveBenchmarkResult,false);assert.equal(r.checks.displacement,1);assert.deepEqual(f.calls,["data get entity PilotProbe Pos","data get entity PilotProbe Dimension","data get entity PilotProbe Health","data get entity PilotProbe Pos","data get entity PilotProbe Dimension","data get entity PilotProbe Health"]);assert.equal(f.bot.closed,true);assert.equal(f.rcon.closed,true);assert.deepEqual(f.controls.at(-1),["forward",false]);assert.equal(f.evidence.status,"passed")});
test("no movement, poor health, and self reports remain failures",async()=>{for(const opts of [{move:false},{health:0},{bad:true}]){const f=fixture(opts);const r=await runQualification(f.args);assert.equal(r.status,"failed");assert.equal(f.evidence.status,"failed");assert.equal(f.bot.closed,true);if(f.rcon)assert.equal(f.rcon.closed,true)}});
test("bounds and adapter failures fail before unsafe calls",async()=>{const f=fixture();await assert.rejects(()=>runQualification({...f.args,actionMs:2001}),/invalid actionMs/);assert.equal(f.calls.length,0);let written;const r=await runQualification({...f.args,createBot:async()=>{throw new Error("secret credential")},writeEvidence:async x=>written=x});assert.equal(r.status,"failed");assert.equal(r.error,"qualification failed");assert.doesNotMatch(JSON.stringify(written),/secret credential/);assert.equal(written.status,"failed")});
test("private evidence is exclusive and contains no injected password",()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"qualify-"));const p=path.join(root,"evidence.json");try{writePrivateEvidence(p,{status:"failed"});assert.equal(fs.statSync(p).mode&0o777,0o600);assert.deepEqual(JSON.parse(fs.readFileSync(p)),{status:"failed"});assert.throws(()=>writePrivateEvidence(p,{status:"passed"}),/EEXIST/);assert.equal(JSON.parse(fs.readFileSync(p)).status,"failed")}finally{fs.rmSync(root,{recursive:true,force:true})}});